common/urls.py
from django.urls import path
from . import views
app_name='common'
urlpatterns = [
    path('',views.index_page,name='index')

]

customer_app/urls.py
from django.urls import path
from . import views
app_name='customer'
urlpatterns = [
    path('home',views.home_page,name='home'),
    path('product',views.product_details,name='product'),
    path('cart',views.cart,name='cart'),
    path('orders',views.my_orders,name='orders'),
    path('password',views.password,name='password'),
    path('profile',views.profile,name='profile')


    
]

eadmin/urls.py
from django.urls import path
from . import views
app_name='eadmin'
urlpatterns = [
    path('home3',views.eadmin,name='home3'),
    path('approve',views.approve_sellers,name='approve'),
    path('view',views.view_sellers,name='view'),
    path('viewcustomers',views.view_customers,name='viewcustomers'),
    path('changepassword',views.change_password,name='changepassword')
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('common.urls')),
    path('customer/',include('customer_app.urls')),
    path('seller/',include('seller_app.urls')),
    path('aj/',include('eadmin.urls'))
    
]

seller_app/urls.py
from django.urls import path
from . import views
app_name='seller'
urlpatterns = [
    path('home2',views.seller_home,name='home2'),
    path('product',views.add_product,name='product'),
    path('catalogus',views.productcatalog,name='catalogus'),
    path('orders',views.my_orders,name='orders'),
    path('stock',views.update_stock,name='stock'),
    path('changepswd',views.change_password,name='changepswd'),
    path('profile',views.seller_profile,name='profile')
    
    
]

common/models.py
from django.db import models

# Create your models here.

customer_app/models.py
from django.db import models

# Create your models here.

eadmin/models.py
from django.db import models

# Create your models here.

seller_app/models.py
from django.db import models

# Create your models here.

common/views.py
from django.shortcuts import render

# Create your views here.
def index_page(request):
    return render(request,'common_templates/index.html')

customer_app/views.py
from django.shortcuts import render

# Create your views here.
def home_page(request):
    return render(request,'customer_templates/home.html')

def product_details(request):
    return render(request,'customer_templates/product_details.html')

def cart(request):
    return render(request,'customer_templates/cart.html')

def my_orders(request):
    return render(request,'customer_templates/my_orders.html')
    
def password(request):
    return render(request,'customer_templates/change_password.html')

def profile(request):
    return render(request,'customer_templates/profile.html')

eadmin/views.py
from django.shortcuts import render

# Create your views here.
def eadmin(request):
    return render(request,'eadmin_templates/home3.html')

def approve_sellers(request):
    return render(request,'eadmin_templates/approve_sellers.html')

def view_sellers(request):
    return render(request,'eadmin_templates/view_sellers.html')

def view_customers(request):
    return render(request,'eadmin_templates/view_customers.html')

def change_password(request):
    return render(request,'eadmin_templates/change_password.html')

seller_app/views.py
from django.shortcuts import render

# Create your views here.
def seller_home(request):
    return render(request,'seller_templates/home2.html')

def add_product(request):
    return render(request,'seller_templates/add_product.html')
    
def productcatalog(request):
    return render(request,'seller_templates/product_catalogus.html')
  
def my_orders(request):
    return render(request,'seller_templates/my_orders.html')

 
def update_stock(request):
    return render(request,'seller_templates/update_stock.html')


def change_password(request):
    return render(request,'seller_templates/change_password.html')


def seller_profile(request):
    return render(request,'seller_templates/seller_profile.html')

common/templates/common_templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><h1>welcome</h1></center>
   <a href="{% url 'customer:home' %}"><h2>customer app</h2></a>
   <a href="{% url 'seller:home2' %}"><h2>seller app</h2></a>
   <a href="{% url 'eadmin:home3' %}"><h2>admin app</h2></a>
</body>
</html>

customer_app/templates/customer_templates/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>cart</h1>
    <a href="{% url 'customer:home' %}"><button type="button">go to home</button></a>
    <a href="{% url 'common:index' %}"><button type="button">go to menu</button></a>
</body>
</html>

customer_app/templates/customer_templates/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>do you want to change password</h1>
    <table cellspacing="8">
        <tr>
            <th>set new password</th>
            <td><input type="text" placeholder="new password"></td>
        </tr>
        <tr>
            <th>conform password</th>
            <td><input type="text" placeholder="conform password"></td>
        </tr>
        <tr></tr>
         <tr>

            <td>
            <a href="{% url 'customer:home' %}"><button type="button">go to home</button></a></td>
          <td><a href="{% url 'common:index' %}"><button type="button">go to menu</button></a></td>
         </tr>
    </table>
</body>
</html>

customer_app/templates/customer_templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><h1>CUSTOMER HOME</h1></center>
    <a href="{% url 'customer:product' %}"><h2>product details</h2></a>
    <a href="{% url 'customer:cart' %}"><h2>cart</h2></a>
    <a href="{% url 'customer:orders' %}"><h2>my orders</h2></a>
    <a href="{% url 'customer:password' %}"><h2> change password</h2></a>
    <a href="{% url 'customer:profile' %}"><h2>profile</h2></a>
    <a href="{% url 'common:index' %}"><button type="button">go to main</button></a>
    
</body>
</html>

customer_app/templates/customer_templates/my_orders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>my orders</h1>
    <a href="{% url 'customer:home' %}"><button type="button">go to home</button></a>
        <a href="{% url 'common:index' %}"><button type="button">go to menu</button></a>
</body>
</html>

customer_app/templates/customer_templates/product_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body> 
    <table cellpadding="10">
        <tr>
   <td> <h3>product 1</h3>
    <img src="{% static 'images/11.jpg' %}">
</td>
<td>
    <h3>product 2</h3>
    <img src="{% static 'images/22.jpg' %}">
</td>
</tr>
<tr>
    <td> <h3>product 3</h3>
     <img src="{% static 'images/33.jpg' %}">
 </td>
 <td>
     <h3>product 4</h3>
     <img src="{% static 'images/images.jpg' %}">  
 </td>
 
 
    <th> <a href="{% url 'customer:home' %}"><button type="button">go to home</button></a>
        <a href="{% url 'common:index' %}"><button type="button">go to menu</button></a></th>
 </tr>
</table>
</body>
</html>

customer_app/templates/customer_templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form>
    <table>
        <tr>
            <th colspan="2"> <center><img src="{% static 'images/qq.jpg' %}"></center> </th>
        </tr>
        <tr>
            <th>name</th>
            <td><input type="text"></td>
        </tr>
        <tr>
            <th>age</th>
            <td><input type="number"></td>
        </tr>
        <tr>
            <th>phone</th>
            <td><input type=" number"></td>
        </tr>
    </table><br><br>
    <a href="{% url 'customer:home' %}"><button type="button">go to home</button></a>
    <a href="{% url 'common:index' %}"><button type="button">go to menu</button></a>
</form>
</body>
</html>

eadmin/templates/eadmin_templates/approve_sellers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>approve sellers</h1>
</body>
</html>

eadmin/templates/eadmin_templates/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>do you want to change password</h1>
    <table cellspacing="8">
        <tr>
            <th>set new password</th>
            <td><input type="text" placeholder="new password"></td>
        </tr>
        <tr>
            <th>conform password</th>
            <td><input type="text" placeholder="conform password"></td>
        </tr>
        <tr></tr>
         <tr>

            <td>
            <a href="{% url 'eadmin:home3' %}"><button type="button">go to home</button></a></td>
          <td><a href="{% url 'common:index' %}"><button type="button">go to menu</button></a></td>
         </tr>
    </table>
</body>
</html>

eadmin/templates/eadmin_templates/home3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>ADMIN APP</h1>
    <a href="{% url 'eadmin:approve' %}"><h2>approve sellers</h2></a>
    <a href="{% url 'eadmin:view' %}"><h2>view sellers</h2></a>
    <a href="{% url 'eadmin:viewcustomers' %}"><h2>view customers</h2></a>
    <a href="{% url 'eadmin:changepassword' %}"><h2>change password</h2></a>
</body>
</html>

eadmin/templates/eadmin_templates/view_customers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>view customers</h1>
</body>
</html>

eadmin/templates/eadmin_templates/view_sellers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>view sellers</h1>
</body>
</html>

seller_app/templates/seller_templates/add_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>add product</h1>
    <input type="text" placeholder="product id"><br><br>
    <a href="{% url 'seller:home2' %}"><button type="button">go to home</button></a>
    <a href="{% url 'common:index' %}"><button type="button">go to menu</button></a>
</body>
</html>

seller_app/templates/seller_templates/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>do you want to change password</h1>
    <table cellspacing="8">
        <tr>
            <th>set new password</th>
            <td><input type="text" placeholder="new password"></td>
        </tr>
        <tr>
            <th>conform password</th>
            <td><input type="text" placeholder="conform password"></td>
        </tr>
        <tr></tr>
         <tr>

            <td>
            <a href="{% url 'seller:home2' %}"><button type="button">go to home</button></a></td>
          <td><a href="{% url 'common:index' %}"><button type="button">go to menu</button></a></td>
         </tr>
    </table>
</body>
</html>

seller_app/templates/seller_templates/home2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>SELLER APP</h1>
    <a href="{% url 'seller:product' %}"><h2>add product</h2></a>
    <a href="{% url 'seller:catalogus' %}"><h2>product catalogus</h2></a>
    <a href="{% url 'seller:orders' %}"><h2>my orders</h2></a>
    <a href="{% url 'seller:stock' %}"><h2>update stock</h2></a>
    <a href="{% url 'seller:changepswd' %}"><h2>change password</h2></a>
    <a href="{% url 'seller:profile' %}"><h2>profile</h2></a>
    
    <a href="{% url 'common:index' %}"><button type="button">go to menu</button></a>
</body>
</html>

seller_app/templates/seller_templates/my_orders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>my orders</h1>
    <br><br>
    <a href="{% url 'seller:home2' %}"><button type="button">go to home</button></a>
    <a href="{% url 'common:index' %}"><button type="button">go to menu</button></a>
</body>
</html>

seller_app/templates/seller_templates/product_catalogus.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>product catalogus</h1>
    <br>
    <br>
    <a href="{% url 'seller:home2' %}"><button type="button">go to home</button></a>
    <a href="{% url 'common:index' %}"><button type="button">go to menu</button></a>
</body>
</html>

seller_app/templates/seller_templates/seller_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form>
        <table>
            <tr>
                <th colspan="2"> <center><img src="{% static 'images/88.jpg' %}"></center> </th>
            </tr>
            <tr>
                <th>name</th>
                <td><input type="text"></td>
            </tr>
            <tr>
                <th>age</th>
                <td><input type="number"></td>
            </tr>
            <tr>
                <th>phone</th>
                <td><input type=" number"></td>
            </tr>
        </table><br><br>
        <a href="{% url 'seller:home2' %}"><button type="button">go to home</button></a>
        <a href="{% url 'common:index' %}"><button type="button">go to menu</button></a>
    </form>
</body>
</html>

seller_app/templates/seller_templates/update_stock.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>update stock</h1>
    <br> 
    <br>
    <a href="{% url 'seller:home2' %}"><button type="button">go to home</button></a>
    <a href="{% url 'common:index' %}"><button type="button">go to menu</button></a>
</body>
</html>